import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local';
import ProtetorDeTela from './_components/ProtetorDeTela';
import { getConfigTotem } from '../sanity/lib/getConfigTotem';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],

});

const fonteasah = localFont({
  src: './fonts/Asah.ttf', 
  variable: '--font-asah', 
});

const fontebold = localFont({
  src: './fonts/Poppins-Bold.ttf', 
  variable: '--font-bold', 
});

const fontelight = localFont({
  src: './fonts/Poppins-Light.ttf', 
  variable: '--font-light', 
});

const fontemedium = localFont({
  src: './fonts/Poppins-Medium.ttf', 
  variable: '--font-medium', 
});

const fonteregular = localFont({
  src: './fonts/Poppins-Regular.ttf',
  variable: '--font-regular',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  // O carrossel de inatividade é o mesmo em todas as telas, então buscamos a
  // configuração aqui no layout e o protetor de tela vale para o projeto todo.
  const config = await getConfigTotem();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${fonteasah.variable} ${fontebold.variable} ${fontelight.variable} ${fontemedium.variable} ${fonteregular.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <ProtetorDeTela imagens={config?.carrosselUrls ?? []} />
      </body>
    </html>
  );
}
